const NOT_FOUND = 404;
const BAD_REQUEST = 400;
const SERVER_ERROR = 500;
const SUCCESS = 200;
const CREATED = 201;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const CONFLICT = 409;

module.exports = {
  NOT_FOUND,
  BAD_REQUEST,
  SERVER_ERROR,
  SUCCESS,
  CREATED,
  UNAUTHORIZED,
  FORBIDDEN,
  CONFLICT,
};
